jarvis_home:
    pattern: /
    defaults: { _controller: JarvisRadiatorBundle:Dashboard:index }

jarvis_dashboard:
    pattern: /dashboard
    defaults: { _controller: JarvisRadiatorBundle:Dashboard:index }