parameters:
#    jarvis_radiator.example.class: petrepatrasc\JarvisRadiatorBundle\Example
    jarvis_radiator.travis.service.class: petrepatrasc\JarvisRadiatorBundle\Service\TravisService

services:
    jarvis.travis:
        class: %jarvis_radiator.travis.service.class%
